import type { Metadata } from "next";
import { Jaldi, Montserrat } from "next/font/google";
import "./globals.css";
import { twMerge } from "tw-merge";

const font = Montserrat({ subsets: ["latin"], variable: "--font-sans" });
const jersey = Jaldi({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-serif",
});
export const metadata: Metadata = {
  title: "Clodron App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          `bg-neutral-900 text-white antialiased font-sans,
          ${jersey.variable} ${font.variable}`,
        )}>
        {children}
      </body>
    </html>
  );
}
