import type { Metadata } from "next";
import { Jersey_20, Montserrat } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const font = Montserrat({ subsets: ["latin"], variable: "--font-sans" });
const jersey = Jersey_20({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Clodron",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "bg-neutral-900 text-white antialiased font-sans",
          jersey.variable,
          font.variable,
        )}>
        {children}
      </body>
    </html>
  );
}
